### ISSUE TITLE
[FEAT] iOS 7차 과제

### ISSUE THREAD

**Issue by jane1choi** [29th-WE-SOPT-iOS-Part/ChoiEunJu#12]
## 📌  Feature Issue

데이터 전달, UIGestureRecognizer 사용하기 입니다.
## 📝  To-do

- [x] `imageView`에 액션 추가
- [ ] `imageView`클릭 시 화면전환
- [ ] 이미지, 영상 타이틀, 조회 수 및 업로드 시간 데이터 전달
- [ ] 버튼 클릭 시 화면 dismiss
