### ISSUE TITLE
[REFACTOR] iOS 3차 과제 리팩토링

### ISSUE THREAD

**Issue by jane1choi** [29th-WE-SOPT-iOS-Part/ChoiEunJu#8]
## 📌  Feature Issue

불필요한 코드 반복을 줄이고, 디테일한 기능 디벨롭을 위한 3차 과제 리팩토링을 진행합니다.
## 📝  To-do

- [X] 코드 반복 줄이기
- [X] 카테고리 셀 클릭 시 색 전환 기능 구현
- [X] 코드 리뷰 반영한 코드 수정
